from .cifar_corrupt import CIFAR_CORRUPT
from .mnist_to_mnist_m import MNIST_to_MNIST_M
from .mnist_to_usps import MNIST_to_USPS
from .office_home import OFFICEHOME
from .portraits import PORTRAITS
from .svhn_to_mnist import SVHN_to_MNIST
from .usps_to_mnist import USPS_to_MNIST
from .upsample import upsample_dataset
from .office_31 import OFFICE31
from .image_clef import IMAGECLEFDA
