from .cifar_corrupt import CIFAR_CORRUPT as CIFAR_CORRUPT
from .mnist_to_mnist_m import MNIST_to_MNIST_M as MNIST_to_MNIST_M
from .mnist_to_usps import MNIST_to_USPS as MNIST_to_USPS
from .office_home import OFFICEHOME as OFFICEHOME
from .portraits import PORTRAITS as PORTRAITS
from .svhn_to_mnist import SVHN_to_MNIST as SVHN_to_MNIST
from .usps_to_mnist import USPS_to_MNIST as USPS_to_MNIST
from .upsample import upsample_dataset as upsample_dataset
from .office_31 import OFFICE31 as OFFICE31
from .image_clef import IMAGECLEFDA as IMAGECLEFDA
from .vis_da17 import VisDA17 as VisDA17
